### ISSUE TITLE
Aarschot Meiser gives error 500

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#325] opened 2017-10-25 19:18 UTC
Sorry,I am on mobile, so I cannot give more information, but I got this report and I can confirm.
Irail.be also show an error.

Link: https://api.irail.be/connections/?from=aarschot&to=meiser and also happening with &format=json

There seems to be some results concatenated with the error 500 message.

**Comment by Bertware** [comment] 2017-10-26 11:01
This was caused by a small walking section in the route. This is a walking section between Haren and Haren-zuid, 2 stations at a few hundred meters from each other, it would be one station if the tracks were a bit closer together. However, this means it's a valid route, and we can't drop it just because it has a walking part.

I fixed the API to support this, however, in the via's this registers as a train with direction 'WALK' and an id of 'WALK'. I don't know how applications are going to respond to this, and *this not definitive*. However since it didn't work before anyway, this might be a good temporary fix, and this needs more discussion with other team members like @pietercolpaert who's not available this week.

I added a `walking` flag to via arrivals and departures. This flag could be used to distinguish a short walk like this from a train. While not definitive, I'm pretty sure the flag's going to stay for things like this. If you already want to support this, I suggest to do the following for now:

- Check for presence of this flag. Use a try-catch or validate the presence, but don't rely on it being there.
- If present and set, treat as walking
- If not present or not set, treat as train

**Comment by ChristopheVersieux** [comment] 2017-10-27 03:25
This as awesome and way better than before!
Thank a lot

**Comment by ChristopheVersieux** [comment] 2017-10-27 03:25
This as awesome and way better than before!
Thank a lot

**Comment by ChristopheVersieux** [comment] 2017-10-27 03:27
Houps my fingers slipped and I "comment and close" before I finished my message.

I guess you want it open before dividing to discuss with other team members, but the fix you made is great.

I wanted to really thank you for your hard work.

**Comment by Bertware** [comment] 2017-11-09 14:28
The definitive fix for this is the walking flag, which has been added to every arrival and departure. This flag is the only reliable way to detect if the part after this departure or before this arrival is a walking part. Any other fields, like the direction and id of the train should be ignored (do not try to parse or read these fields in this case). Future updates might add the walking time in this field. Therefore I recommend you use the following test:
`walking == 0` means it's a train (non-walking). `walking > 0` means it's a walking part.

The documentation will be updated with new fields and information once everything is final.

**Closed by Bertware** 2017-11-09 14:28 UTC
Labels: bug, confirmed
