### ISSUE TITLE
Connections from or to Kapellen (B) give results from Capellen (L)

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#254] opened 2016-08-15 11:16 UTC
When requesting connections from or to Kapellen in Belgium, the API result displays connections from or to Capellen in Luxembourg. This is probably due to the fact that both stations local `name` is `Kapellen`. (Although in EN, FR and NL the Luxembourg town is called `Capellen`.)

e.g. `http://api.irail.be/connections/?lang=fr&to=BE.NMBS.008812005&from=BE.NMBS.008821535`

**Comment by pietercolpaert** [comment] 2016-08-16 06:15
Duplicate of iRail/hyperRail#122 and iRail/iRail#254

**Closed by pietercolpaert** 2016-08-16 06:15 UTC
Labels: confirmed

**Comment by pietercolpaert** [comment] 2016-08-16 07:02
This is fixed now @jncn!

**Comment by jncn** [comment] 2016-08-16 09:30
Thx @pietercolpaert!
