### ISSUE TITLE
Disturbances broken depending on the params

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#522] opened 2024-05-13 20:27 UTC
Disturbances currently gives an error on production when:
- `format=json`
- No `lang` param is specified
- `lang=de`
- A `lineBreakCharacter` is specified

So basically only this url works now (with nl/en/fr as value): https://api.irail.be/v1/disturbances/?lang=en

**Comment by Bertware** [comment] 2024-05-13 22:24
The cause for this issue is an unhandled case in the source data (missing id on a disturbance). English is the default, and happened to be cached better/later in the fallback cache (which handles downtime/issues on the upstream side), but ultimately all requests failed. Should be fixed now.

**Closed by Bertware** 2024-05-13 22:24 UTC

**Comment by jncn** [comment] 2024-05-13 23:00
Faster than his shadow! Way to go @Bertware ❤️
