### ISSUE TITLE
Error for vehicles going to Visé

### ISSUE THREAD

**Issue by koenvb-olympus** [iRail/iRail#390] opened 2019-11-13 16:06 UTC
It looks like the vehicle information for trains between Liege-Guillemins and Wezet (Visé) can't be retrieved.

Example:

https://api.irail.be/vehicle?format=json&lang=nl&id=BE.NMBS.S435370&date=131119

{
  "error": 500,
  "message": "Could not get data. Please report this issue at https://github.com/irail/irail/issues/new"
}

It seems to happen for most trains to Visé, but not all. On the NMBS website I do get the stop between the stations.

**Comment by Bertware** [comment] 2019-11-24 18:49
This problem is caused by a missing station:  `Could not match 'Maastricht Randwijck' with a station id in iRail`

**Comment by Bertware** [comment] 2019-11-24 19:19
This issue has been resolved by fixing https://github.com/iRail/stations/issues/154 and updating the stations database on the server. Thanks for reporting it, the example link was extremely helpful!

**Closed by Bertware** 2019-11-24 19:19 UTC
Labels: Bug, Confirmed, Prio: High
