### ISSUE TITLE
Some compositions fail at parsing

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#437] opened 2021-03-01 11:39 UTC
e.g. https://staging.api.irail.be/composition/?lang=nl&id=BE.NMBS.L5011 gives this error:
```xml 
<error code="404">Could not find a station with id 00.</error>
```
But there is an actual result on https://trainmapjs.azureedge.net/data/composition/5011:
```json
[{"ptCarFrom":{"id":459,"uicCode":"8844008","fromName":"Géronstère - Géronstère"},"ptCarTo":{"id":1177,"uicCode":"8844008","fromName":"Verviers-C - Verviers-C"},"confirmedBy":"Planning","materialUnits":[{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"MR 62-66","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":24,"materialDiagram":"MR","isLocoInUse":true,"tractionPosition":1,"positionInComposition":1,"typeDescriptionFr":"AM 62-66","hasPriorityPlaces":true,"brutoWeight":130,"lengthInMeter":47,"hasPrmSection":false,"standingPlacesSecondClass":60,"standingPlacesFirstClass":16,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":152,"seatsFirstClass":28,"isDrivingCabinetAvailable":false,"hasServiceSection":true,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":true,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":true,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"parentMaterialTypeName":"AM62-66","subTypeDescriptionFr":"AM 62-66","subTypeDescriptionNl":"MR 62-66","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false},{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"MR 62-66","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":24,"materialDiagram":"MR","isLocoInUse":true,"tractionPosition":1,"positionInComposition":2,"typeDescriptionFr":"AM 62-66","hasPriorityPlaces":true,"brutoWeight":130,"lengthInMeter":47,"hasPrmSection":false,"standingPlacesSecondClass":60,"standingPlacesFirstClass":16,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":152,"seatsFirstClass":28,"isDrivingCabinetAvailable":false,"hasServiceSection":true,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":true,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":true,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"parentMaterialTypeName":"AM62-66","subTypeDescriptionFr":"AM 62-66","subTypeDescriptionNl":"MR 62-66","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false},{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"MR 62-66","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":9,"materialDiagram":"MR","isLocoInUse":true,"tractionPosition":2,"positionInComposition":3,"typeDescriptionFr":"AM 62-66","hasPriorityPlaces":true,"brutoWeight":130,"lengthInMeter":47,"hasPrmSection":false,"standingPlacesSecondClass":60,"standingPlacesFirstClass":16,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":152,"seatsFirstClass":28,"isDrivingCabinetAvailable":false,"hasServiceSection":true,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":true,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":true,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"parentMaterialTypeName":"AM62-66","subTypeDescriptionFr":"AM 62-66","subTypeDescriptionNl":"MR 62-66","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false},{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"MR 62-66","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":9,"materialDiagram":"MR","isLocoInUse":true,"tractionPosition":2,"positionInComposition":4,"typeDescriptionFr":"AM 62-66","hasPriorityPlaces":true,"brutoWeight":130,"lengthInMeter":47,"hasPrmSection":false,"standingPlacesSecondClass":60,"standingPlacesFirstClass":16,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":152,"seatsFirstClass":28,"isDrivingCabinetAvailable":false,"hasServiceSection":true,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":true,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":true,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"parentMaterialTypeName":"AM62-66","subTypeDescriptionFr":"AM 62-66","subTypeDescriptionNl":"MR 62-66","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false}]},{"ptCarFrom":{"id":1177,"uicCode":"8849023","fromName":"Verviers-C - Verviers-C"},"ptCarTo":{"id":598,"uicCode":"8849023","fromName":"\" - \""},"confirmedBy":"Planning","materialUnits":[{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"MR 62-66","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":9,"materialDiagram":"MR","isLocoInUse":true,"tractionPosition":1,"positionInComposition":1,"typeDescriptionFr":"AM 62-66","hasPriorityPlaces":true,"brutoWeight":130,"lengthInMeter":47,"hasPrmSection":false,"standingPlacesSecondClass":60,"standingPlacesFirstClass":16,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":152,"seatsFirstClass":28,"isDrivingCabinetAvailable":false,"hasServiceSection":true,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":true,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":true,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"parentMaterialTypeName":"AM62-66","subTypeDescriptionFr":"AM 62-66","subTypeDescriptionNl":"MR 62-66","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false},{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"MR 62-66","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":9,"materialDiagram":"MR","isLocoInUse":true,"tractionPosition":1,"positionInComposition":2,"typeDescriptionFr":"AM 62-66","hasPriorityPlaces":true,"brutoWeight":130,"lengthInMeter":47,"hasPrmSection":false,"standingPlacesSecondClass":60,"standingPlacesFirstClass":16,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":152,"seatsFirstClass":28,"isDrivingCabinetAvailable":false,"hasServiceSection":true,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":true,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":true,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"parentMaterialTypeName":"AM62-66","subTypeDescriptionFr":"AM 62-66","subTypeDescriptionNl":"MR 62-66","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false}]},{"ptCarFrom":{"id":598,"uicCode":"8015345","fromName":"\" - \""},"ptCarTo":{"id":1,"uicCode":"8015345","fromName":"Aachen Hbf - Aachen Hbf"},"confirmedBy":"Itris","materialUnits":[{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"AM 62-66 Vehicle a","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":9,"materialNumber":648,"materialDiagram":"MR","parentUicCode":"948806664801","uicCode":"948806664819","isLocoInUse":true,"inDirection":true,"tractionPosition":1,"positionInComposition":1,"materialSubTypeName":"AM62-66_a","typeDescriptionFr":"AM 62-66 Vehicle a","parentMaterialSubTypeName":"AM62-66","hasPriorityPlaces":true,"brutoWeight":65,"lengthInMeter":23,"hasPrmSection":false,"standingPlacesSecondClass":28,"standingPlacesFirstClass":0,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":102,"seatsFirstClass":0,"isDrivingCabinetAvailable":false,"hasServiceSection":false,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":false,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":false,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"subTypeDescriptionFr":"AM 62-66 Vehicle a","subTypeDescriptionNl":"AM 62-66 Vehicle a","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false},{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"AM 62-66 Vehicle b","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":9,"materialNumber":648,"materialDiagram":"MR","parentUicCode":"948806664801","uicCode":"948806664827","isLocoInUse":true,"inDirection":true,"tractionPosition":1,"positionInComposition":2,"materialSubTypeName":"AM62-66_b","typeDescriptionFr":"AM 62-66 Vehicle b","parentMaterialSubTypeName":"AM62-66","hasPriorityPlaces":true,"brutoWeight":65,"lengthInMeter":23,"hasPrmSection":false,"standingPlacesSecondClass":14,"standingPlacesFirstClass":13,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":58,"seatsFirstClass":20,"isDrivingCabinetAvailable":false,"hasServiceSection":true,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":true,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":true,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"subTypeDescriptionFr":"AM 62-66 Vehicle b","subTypeDescriptionNl":"AM 62-66 Vehicle b","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false},{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"AM 62-66 Vehicle a","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":0,"materialNumber":646,"parentUicCode":"948806664603","uicCode":"948806664611","isLocoInUse":false,"inDirection":true,"tractionPosition":2,"positionInComposition":3,"materialSubTypeName":"AM62-66_a","typeDescriptionFr":"AM 62-66 Vehicle a","parentMaterialSubTypeName":"AM62-66","hasPriorityPlaces":true,"brutoWeight":65,"lengthInMeter":23,"hasPrmSection":false,"standingPlacesSecondClass":28,"standingPlacesFirstClass":0,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":102,"seatsFirstClass":0,"isDrivingCabinetAvailable":false,"hasServiceSection":false,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":false,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":false,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"subTypeDescriptionFr":"AM 62-66 Vehicle a","subTypeDescriptionNl":"AM 62-66 Vehicle a","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false},{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"AM 62-66 Vehicle b","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":0,"materialNumber":646,"parentUicCode":"948806664603","uicCode":"948806664629","isLocoInUse":false,"inDirection":true,"tractionPosition":2,"positionInComposition":4,"materialSubTypeName":"AM62-66_b","typeDescriptionFr":"AM 62-66 Vehicle b","parentMaterialSubTypeName":"AM62-66","hasPriorityPlaces":true,"brutoWeight":65,"lengthInMeter":23,"hasPrmSection":false,"standingPlacesSecondClass":14,"standingPlacesFirstClass":13,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":58,"seatsFirstClass":20,"isDrivingCabinetAvailable":false,"hasServiceSection":true,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":true,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":true,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"subTypeDescriptionFr":"AM 62-66 Vehicle b","subTypeDescriptionNl":"AM 62-66 Vehicle b","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false}]},{"ptCarFrom":{"id":341,"fromName":"Den Haag HS - Den Haag-HS"},"ptCarTo":{"id":459,"fromName":"Géronstère - Géronstère"},"confirmedBy":"Atlas","materialUnits":[{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"AM 62-66 Vehicle b","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":9,"materialNumber":646,"materialDiagram":"MR","parentUicCode":"948806664603","uicCode":"948806664611","isLocoInUse":true,"inDirection":false,"tractionPosition":1,"positionInComposition":1,"materialSubTypeName":"AM62-66_b","typeDescriptionFr":"AM 62-66 Vehicle b","parentMaterialSubTypeName":"AM62-66","hasPriorityPlaces":true,"brutoWeight":65,"lengthInMeter":23,"hasPrmSection":false,"standingPlacesSecondClass":14,"standingPlacesFirstClass":13,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":58,"seatsFirstClass":20,"isDrivingCabinetAvailable":false,"hasServiceSection":true,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":true,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":true,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"subTypeDescriptionFr":"AM 62-66 Vehicle b","subTypeDescriptionNl":"AM 62-66 Vehicle b","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false},{"hasReadingLights":false,"hasFoldingSeats":false,"hasAssistanceButtons":false,"hasToilets":true,"hasTables":true,"hasSecondClassOutlets":false,"hasFirstClassOutlets":false,"hasHeating":true,"hasAirco":false,"typeDescriptionNl":"AM 62-66 Vehicle a","tractionType":"AM/MR","pullPushType":"X","diagramServiceNumber":9,"materialNumber":646,"materialDiagram":"MR","parentUicCode":"948806664603","uicCode":"948806664629","isLocoInUse":true,"inDirection":false,"tractionPosition":1,"positionInComposition":2,"materialSubTypeName":"AM62-66_a","typeDescriptionFr":"AM 62-66 Vehicle a","parentMaterialSubTypeName":"AM62-66","hasPriorityPlaces":true,"brutoWeight":65,"lengthInMeter":23,"hasPrmSection":false,"standingPlacesSecondClass":28,"standingPlacesFirstClass":0,"seatsCoupeSecondClass":0,"seatsCoupeFirstClass":0,"seatsSecondClass":102,"seatsFirstClass":0,"isDrivingCabinetAvailable":false,"hasServiceSection":false,"withTowBar":false,"withTractionCoupling":false,"hasBikeSection":false,"isEquipedForMux":false,"isSecondClass":true,"isFirstClass":false,"materialSubTypeSuffix":" ","withAutomaticCoupling":false,"subTypeDescriptionFr":"AM 62-66 Vehicle a","subTypeDescriptionNl":"AM 62-66 Vehicle a","canPassToNextUnit":true,"hasCameras":false,"hasRealTimeInformationScreens":false,"hasWasteBins":true,"hasSemiAutomaticInteriorDoors":false,"hasLuggageSection":false}]}]
```

I guess this has something to do with the missing `uicCode`:
```json
"ptCarFrom": {
      "id": 341,
      "fromName": "Den Haag HS - Den Haag-HS"
},
"ptCarTo": {
      "id": 459,
      "fromName": "Géronstère - Géronstère"
}
```

**Comment by Bertware** [comment] 2021-03-01 18:13
It's indeed caused by the missing UIC code. The 9-digit id is determined by adding two zeroes after the country identifier, so in this case it adds 2 zeroes to nothing, then throws an error because '00' isn't a station id.  We could try searching for the station if an id isn't present, but it still wouldn't guarantee a match (They write Géronstère when they mean Spa-Géronstère, so the others might not be accurate either). In any case your app should have a graceful fallback for any server errors (and I'd even be careful with the data as well, e.g. "empty" trains)

**Comment by jncn** [comment] 2021-03-01 18:32
Great! Missing stations are okay.

I've written a fair share of logic already, indeed 😜 
* Self-written data set for features per unit
* Fixed the bug with duplicate station id's by combining it with the /vehicle or /connections endpoint (which I'm requesting in anycase)
* Filtering out unrealistic compositions, e.g. only locs
* An attempt at positioning a loc or control car as first unit, when the order is messed up (tricky though, because I'm not sure if it should be the loc or the control car)

Looking forward to ship it, but still some work to do!

**Comment by Muspah** [comment] 2021-11-17 10:45
NMBS ID's seems to match with Infrabel's open data > https://opendata.infrabel.be/explore/dataset/operationele-punten-van-het-newterk/information/?disjunctive.classification

**Comment by Muspah** [comment] 2021-11-17 18:20
NMBS occasionally returns an internal point, rather then an actual station (I'm not sure how to translate, we would call it a 'dienstregelpunt' in Holland). This breaks the iRail API too. For example:

![image](https://user-images.githubusercontent.com/43544407/142259126-d4c4cff3-57df-4f77-a74a-47276b672683.png)
![image](https://user-images.githubusercontent.com/43544407/142259170-2bd596bb-5529-4e63-b6f1-dffb5b88d735.png)

**Comment by Bertware** [comment] 2021-11-19 20:24
Interesting to see that Infrabel classifies it as a `station`, and not as a `service installation` or `service stop` Infrabel lists 413 stations, iRail contains 679 stations. It might be interesting to compare the data, and see if we are missing "real" stations. These technical stations shouldn't be included in the traveller-oriented iRail-stations, as it would become confusing with autocompletes, but the abbreviations and official translations which Infrabel has for passenger stations seem very valueable.

We might be able to add this dataset to the iRail API, then lookup stations in the infrabel dataset in case they are not present in iRail/Stations. Might need to think how that would be represented in the API response though.

**Comment by Muspah** [comment] 2021-11-19 22:00
Few words about myself, I used to have a professional background in the Dutch railway system, and started working on integrating Belgian data into some applications that I'm running as part of a hobby since I'm living in Belgium most of my time. Both systems have a lot in common, but there's a lot to learn for me in terminology, et cetera. We don't talk about a "bundel" like Infrabel, for example.

I'm not a big user for iRail, but use some endpoints (disruptions for example) and sometimes use the codebase for reference. Just trying to log things that I find here that might be intereseting for iRail too. Don't feel obligated to include parts into your API :)

We're seeing those non-passenger stations multiple times a day. I'm not sure if I'm just going to map them to the nearest station, or something else. We're logging all the NMBS composition messages as CSV, if you ever want to look into things............

**Comment by Bertware** [comment] 2024-05-01 08:52
Fixed with the new iRail codebase

**Closed by Bertware** 2024-05-01 08:52 UTC
Labels: Wontfix, Confirmed, Bug
