### ISSUE TITLE
Unannounced API changes for /liveboard causing troubles

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#243] opened 2016-07-27 22:34 UTC
After today's deploy, `<vehicle>BE.NMBS.IC743</vehicle>` has become `<vehicle URI="http://irail.be/vehicle/IC743">IC743</vehicle>`, causing a crash in Railer.
Please change this to: `<vehicle URI="http://irail.be/vehicle/IC743">BE.NMBS.IC743</vehicle>`, with `BE.NMBS.` included.
Thanks!

**Comment by pietercolpaert** [comment] 2016-07-28 06:08
Thanks for the nudge and sadly I was sleeping when you creating this issue.  Can you check whether my last commit fixed it again?

**Comment by jncn** [comment] 2016-07-28 07:15
You sleep? 😉
It works again, thanks!

**Comment by Bertware** [comment] 2017-09-21 09:18
@jncn We're currently working hard on fixing up a whole lot of iRail issues, and moving to a new (faster) server.
While we will offer clear documentation on some possible breaking changes later this week, I came across this issue already.

The following change would happen to the response, which might break railer:
```
<vehicle locationX="4.142966" locationY="51.171472">BE.NMBS.IC3232</vehicle>
```
to
```
<vehicle locationX="4.142966" locationY="51.171472" id="BE.NMBS.IC3232" URI="http://irail.be/vehicle/IC3232">IC3232</vehicle>
```

Would it be possible to make railer accept both BE.NMBS.IC3232
 and IC3232 (required for transitioning)?

@ChristopheVersieux the JSON will change in the following way:
from
```
"vehicle": "BE.NMBS.IC3232",
"vehicleinfo": {

    "locationX": "4.142966",
    "locationY": "51.171472",
    "name": "BE.NMBS.IC3232"

},
```
to
```
"vehicle": "IC3232",
"vehicleinfo": {
    "locationX": "4.142966",
    "locationY": "51.171472",
    "name": "IC3232",
    "id": "BE.NMBS.IC3232",
    "@id": "http://irail.be/vehicle/IC3232"
},
```
Please make sure this change wouldn't crash the application.

Complete (new) documentation, a list of all changes, and access to a test server will be communicated later on to test apps against the fixed API, but for now this seems like the largest (breaking) change.

**Comment by jncn** [comment] 2017-09-21 09:30
Thanks for the update, @Bertware. I made Railer compatible with both formats right after this issue came up. Safe for me to do your changes.

**Comment by ChristopheVersieux** [comment] 2017-09-21 09:58
It's very hard to say without testing more, but I don't think this might cause any issue. In worst case, I used replace(""BE.NMBS.,""), so this should not have any impact.

But I always fear this kind of change without more tests

**Comment by Bertware** [comment] 2017-09-21 10:01
@ChristopheVersieux Testing will be possible later on! :wink:

**Comment by Bertware** [comment] 2017-09-22 09:41
Last night we quickly fixed SSL certificates on the new server, and did some quick testing.
The new server is now available at https://188.226.174.116/.
Accessing it through its IP Address might cause certificate errors, either ignore them or add an entry to your hosts file while debugging.
Please do not use a fixed IP address in any production environment.
This is just a quick heads-up, official communication through the blog and mailing list will follow.

@ChristopheVersieux I quickly tested BeTrains and there was a crash on the vehicle page I believe, not sure if this was caused by API changes.

JSON changes in vehicle endpoint:
```
<     "name": "L782"
---
>     "name": "BE.NMBS.L782",
>     "shortname": "L782",
>     "@id": "http://irail.be/vehicle/L782"
```

XML changes in vehicle endpoint
```
<   <vehicle locationX="3.574515" locationY="51.181333">L782</vehicle>
---
>   <vehicle URI="http://irail.be/vehicle/L782" locationX="3.574515" locationY="51.181333" shortname="L782">BE.NMBS.L782</vehicle>
```

Full documentation is available on docs.irail.be

**Comment by ChristopheVersieux** [comment] 2017-09-23 09:53
Hello guys,
Just coming back from trip abroad, need some time to rest, but I can see that the application has some issues that need to be fixed, some stations are not working anymore and I have a lot of issues when making random search.

Seems to be working sometimes, so that's not a issue in the format. More information coming soon if I find time to open the code

**Comment by ChristopheVersieux** [comment] 2017-09-23 16:42
I don't know if this is linked to your changes, but the JSON is not correct anymore: https://github.com/iRail/iRail/issues/311

**Comment by Bertware** [comment] 2017-09-23 16:51
Unrelated as far as I know, will try and get it fixed by Monday as well.

**Closed** 2017-09-27 10:44 UTC
