### ISSUE TITLE
Error 500 for all Connections requests

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#320] opened 2017-10-16 10:12 UTC
Hello,

I received a lot of feedback from my users that the app was not working anymore.
I tried some quick checks, and I received an error 500:

https://api.irail.be/connections/?from=mons&to=tournai&timesel=departure&format=json&lang=en&fast=false&typeOfTransport=trains&alerts=false&results=6

I checked https://status.irail.be/ and the connection is in red.

I can see:

down | 2017-10-16 07:36:33 | Internal Server Error | 2 hrs, 35 mins.
This looks like the issue is resolved, but this is not the case.

Is there something I can do to help?

**Comment by Bertware** [comment] 2017-10-16 11:04
Duplicate of #319 
Already working on it: the NMBS decided to take a webpage offline, but we were using this page to get our information on connections. We're currently writing a new parser to get data from another place ;)

**Closed by Bertware** 2017-10-16 11:04 UTC
Labels: duplicate
