### ISSUE TITLE
NMBS updated authentication system for compositions

### ISSUE THREAD

**Issue by mikemarchal** [iRail/iRail#460] opened 2022-07-25 23:33 UTC
'You do not have permission to view this directory or page.'
https://trainmap.belgiantrain.be/data/composition/XXX
My guess is they updated some new sort of authentication, see trainmap reqeusts,
they now include 'auth-code'

**Comment by Muspah** [comment] 2022-07-26 13:35
Seems to be a static key, we're running for multiple hours now on the same key without problems.

**Comment by Bertware** [comment] 2022-07-27 09:20
Should be fixed! https://api.irail.be/composition/?lang=en&id=BE.NMBS.L2781

**Comment by Bertware** [comment] 2022-07-27 09:23
Special thanks to @mikemarchal for the clear issue description including a suggested fix, the only thing left to do was coding it!

**Comment by Bertware** [comment] 2022-07-27 10:44
Re-opening since the key is rotated on a regular basis, thanks @Muspah for signalling this.

https://github.com/iRail/iRail/commit/ec45d3bd81bcbcdbb04b71d21153040526e130e7#commitcomment-79534099

**Comment by Muspah** [comment] 2022-07-27 10:54
I've added the key to my logger yesterday and faced 401's again this morning. Guessing the rotation is done on a daily basis.

**Closed** 2022-07-28 21:06 UTC

**Comment by Bertware** [comment] 2022-07-28 21:10
Fixed, this time for real! Note that the current implementation is a quick-fix, which caches the authentication key for half an hour so we don't cause a significant load on the NMBS servers. This means however that the key can be incorrect for up to 30 minutes, meaning that compositions might not work for up to 30 minutes a day. The real fix for that issue is to clear the cached key upon a 401 response.

**Comment by Muspah** [comment] 2022-07-30 12:36
Key change seems to happen at 2AM local time, so I would guess 12AM UTC.

**Comment by mikemarchal** [comment] 2022-07-31 21:37
> Key change seems to happen at 2AM local time, so I would guess 12AM UTC.

Or maybe nothing to do with UTC... the nightly interruption of train service ;P

**Comment by Muspah** [comment] 2022-07-31 21:51
Would be possible, but even when there are still trains running, the key changes. My guess is that it’s a simple cron for the trainmap unrelated to backend planning systems.

**Comment by mikemarchal** [comment] 2022-07-31 22:10
> Would be possible, but even when there are still trains running, the key changes. My guess is that it’s a simple cron for the trainmap unrelated to backend planning systems.

It would still be logic tho, when opening trainmap at 00:59 it doesn't break at 01:00 in CET time.

**Comment by Muspah** [comment] 2022-07-31 22:17
We will find out in the end of october, when DST is over. SNCB can always take a look at the Dutch system and start providing pushfeeds with data so we don't have to poll anymore, lol (or take a look at NetworkRail in the UK, ...)

**Comment by Muspah** [comment] 2022-08-10 11:38
NMBS did something today, trainmap rotates between two keys every few seconds. Even their own frontend breaks if you happen to click on a trip or composition on the second that the other key is active then when you've opened the page.

**Comment by Bertware** [comment] 2022-08-10 16:57
I won't fix this as they clearly are trying to prevent automated scraping - iRail does however cache every composition for 6 hours, and non-confirmed compositions for 5 minutes, meaning the loads coming from iRail should not be significant. If anyone else is running local iRail setups, or any other setups scraping this data, I'd encourage them to ensure there is a form of caching/rate-limiting/... of outgoing requests as to not cause any issues for the original service.

**Comment by Muspah** [comment] 2022-08-10 17:00
It breaks their own front-end, it seems like a simple bug. Just dumped it here as a heads-up for others if iRail returns errors.

**Comment by Muspah** [comment] 2022-08-11 07:40
Issue resolved, the key seems to be static again.

**Comment by Muspah** [comment] 2022-08-28 16:09
Bit late but heads up: same issue today. Key rotating between two values.
