### ISSUE TITLE
Errors in JSON on Staging

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#493] opened 2023-10-13 08:00 UTC
Some `connections` give a bunch of parsing errors. 

e.g.: https://staging.api.irail.be/connections/?lang=en&format=json&from=BE.NMBS.008833001&to=BE.NMBS.008891702&timesel=departure

```
<br />
<b>Warning</b>:  Undefined array key "lead" in <b>/var/www/staging.api.irail.be/src/api/data/NMBS/tools/HafasCommon.php</b> on line <b>262</b><br />
<br />
<b>Warning</b>:  Undefined array key "lead" in <b>/var/www/staging.api.irail.be/src/api/data/NMBS/tools/HafasCommon.php</b> on line <b>262</b><br />
<br />
<b>Warning</b>:  Undefined array key "lead" in <b>/var/www/staging.api.irail.be/src/api/data/NMBS/tools/HafasCommon.php</b> on line <b>262</b><br />
<br />
<b>Warning</b>:  Undefined array key "lead" in <b>/var/www/staging.api.irail.be/src/api/data/NMBS/tools/HafasCommon.php</b> on line <b>262</b><br />
<br />
<b>Warning</b>:  Undefined array key "lead" in <b>/var/www/staging.api.irail.be/src/api/data/NMBS/tools/HafasCommon.php</b> on line <b>262</b><br />
<br />
<b>Warning</b>:  Undefined array key "lead" in <b>/var/www/staging.api.irail.be/src/api/data/NMBS/tools/HafasCommon.php</b> on line <b>262</b><br />
```

**Comment by Bertware** [comment] 2023-10-27 18:04
The continuous deployment for staging got stuck, should be fixed now (unless this was caused by another bug).

**Comment by jncn** [comment] 2023-10-28 12:26
The JSON errors are gone now indeed, but now XML has an error:

```
This page contains the following errors:

error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.
```

**Comment by Bertware** [comment] 2024-05-01 08:53
Staging has been updated to be a completely different server with exactly the same setup, so it'll always be in sync with the development branch from now on. This should prevent issues like this in the future

**Closed by Bertware** 2024-05-01 08:53 UTC
