### ISSUE TITLE
Add properties to Vehicle object

### ISSUE THREAD

**Issue by ikbenmartijn** [iRail/iRail#27] opened 2013-01-08 10:24 UTC
For each stop show:
- delay
- delay forecast for future stops
Delays are only visible in Departures/Arrivals for now. It's more logical to keep delays attached to the Vehicle object.

- has_arrived (BOOL)
- has_left (BOOL)
These two properties make it easier to determine if a (delayed) train is currently parked in a station or on it's way to another.

**Comment by jncn** [comment] 2015-12-28 14:36
Vehicles do show delays and platforms for each stop.
I don't think `has_arrived` and `has_left ` are needed once #92 is fixed.

**Comment by pietercolpaert** [comment] 2016-01-02 03:07
Will close this as a duplicate of #92. Delay right now has been fixed

**Closed by pietercolpaert** 2016-01-02 03:07 UTC
